# Generated by Django 6.0.4 on 2026-10-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Generated Landing Page', max_length=255)),
                ('target_url', models.URLField(max_length=500)),
                ('ad_text', models.TextField(blank=True, default='')),
                ('ad_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('variant', models.CharField(choices=[('standard', 'Standard Modern SaaS'), ('high_urgency', 'High Urgency / Conversion Focus'), ('social_proof', 'Social Proof & Trust Heavy'), ('minimalist', 'Minimalist & Clean')], default='standard', max_length=50)),
                ('generated_html', models.TextField()),
                ('cro_score', models.IntegerField(default=85)),
                ('cro_feedback', models.TextField(blank=True, default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
